[package]
name = "fenris-sparse"
version = "0.0.1"
authors = ["Andreas Longva <longva@cs.rwth-aachen.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.28"
nalgebra-sparse = "0.4"
rayon = "1.3"
num = "0.4"
fenris-paradis = { path = "../fenris-paradis" }

[dev-dependencies]
proptest = "1.0"
util = { path = "../util" }