[package]
name = "fenris-solid"
version = "0.0.1"
authors = ["Andreas Longva <andreas.b.longva@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
fenris = { path = ".." }
serde = "1.0.126"
numeric_literals = "0.2.0"

[dev-dependencies]
matrixcompare = "0.3.0"
fenris-optimize = { path = "../fenris-optimize" }