[package]
name = "fenris-solid"
version = "0.1.0"
authors = ["Andreas Longva <andreas.b.longva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fenris = { path = "../" }
serde = "1.0.126"
numeric_literals = "0.2.0"

[dev-dependencies]
matrixcompare = "0.3.0"
fenris-optimize = { path = "../fenris-optimize" }