[package]
name = "fenris-optimize"
version = "0.0.1"
authors = ["Andreas Longva <longva@cs.rwth-aachen.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
nalgebra = { version = "0.28", features = ["compare"] }
numeric_literals = "0.2.0"
itertools = "0.9"
log = "0.4"

[dev-dependencies]
matrixcompare = "0.3.0"