[package]
name = "fenris-traits"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core traits used by fenris"

[dependencies]
nalgebra = { workspace = true, default-features = false }