[package]
name = "fenris-geometry"
version = "0.1.0"
authors = ["Andreas Longva <longva@cs.rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
nalgebra = "0.21"
serde = { version="1.0", features = [ "derive" ] }
numeric_literals = { git = "https://github.com/Andlon/numeric_literals", rev = "c43f098e617f0b768b43c185711ed106f4170cd7" }
nested-vec = { path="../nested-vec" }
vtkio = { version = "0.3", optional = true }
proptest = { version="0.9", optional = true }
# TODO: num isn't really necessary, except for some vtk stuff
num = "0.2"

[dev-dependencies]
matrixcompare = { git = "https://github.com/Andlon/matrixcompare.git", rev="dcda6ac11c3c289866e1ac5ee9da3772ab1e3089" }
util = { path="../util" }
