[package]
name = "fenris-geometry"
version = "0.0.1"
authors = ["Andreas Longva <longva@cs.rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
nalgebra = "0.28"
serde = { version="1.0", features = [ "derive" ] }
numeric_literals = "0.2.0"
fenris-nested-vec = { path="../fenris-nested-vec" }
proptest = { version="1.0", optional = true }

[dev-dependencies]
matrixcompare = "0.3"
util = { path="../util" }
